package io.alittlebrighter.gomobileexample;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

import go.testsdk.Testsdk;

public class SetupActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_setup);

        // constant from go library
        ((TextView) findViewById(R.id.title)).setText(Testsdk.Title);

        final EditText myName = (EditText) findViewById(R.id.myName);
        final TextView greeting = (TextView) findViewById(R.id.greeting);
        findViewById(R.id.buttonGreet).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    // function that throws an exception
                    greeting.setText(Testsdk.SayHello(myName.getText().toString()));
                } catch (Exception e) {
                    greeting.setText(e.getMessage());
                }
            }
        });

        final EditText one = (EditText) findViewById(R.id.one);

        // save a value through the Go library (does not persist app restarts)
        Testsdk.SaveVal(9);
        // and retrieve it
        one.setText(String.valueOf(Testsdk.RetrieveVal()));

        final EditText two = (EditText) findViewById(R.id.two);

        // pointer to class generated by the go library
        Testsdk.MathResult firstResult = Testsdk.MathResultPointer();
        // getter for property that isn't accessible by the generated class
        two.setText(String.valueOf(firstResult.Divisor()));

        final TextView result = (TextView) findViewById(R.id.result);

        findViewById(R.id.buttonAdd).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                result.setText(Testsdk.PrintResult(Testsdk.MathResultPointer(), Integer.parseInt(one.getText().toString()), Integer.parseInt(two.getText().toString())));
            }
        });

        findViewById(R.id.buttonSubtract).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                result.setText(Testsdk.PrintResult(new MyResult(), Integer.parseInt(one.getText().toString()), Integer.parseInt(two.getText().toString())));
            }
        });

        // enable gyro from Go library
        Testsdk.EnableGyro();

        findViewById(R.id.buttonGyro).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                result.setText(Testsdk.GetGyroResult());
            }
        });
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        Testsdk.DisableGyro();
    }
}
